[project]
name = "lastfm_stats"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aenum>=3.1.15",
    "cuid2>=2.0.1",
    "cutlet>=0.5.0",
    "dash>=2.18.2",
    "numpy>=2.2.1",
    "pandas>=2.2.3",
    "plotly>=5.24.1",
    "pydantic>=2.10.5",
    "pylast>=5.3.0",
    "pytest>=8.3.4",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "unidic-lite>=1.0.8",
]

[project.scripts]
lastfm_stats = "lastfm_stats.main:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/lastfm_stats"]


[tool.pytest.ini_options]
pythonpath = [
    "src"
]

[tool.pyright]
include = ["src"]
exclude = [
    "**/node_modules",
    "**/__pycache__",
    "**/.idea",
    "**/.pytest_cache",
    "**/tests",
    "**/.git",
    "**/playground"
]
defineConstant = { DEBUG = true }
stubPath = "src/stubs"

reportMissingImports = "error"
reportMissingTypeStubs = false

pythonVersion = "3.13.1"
pythonPlatform = "Darwin"