[tool.poetry]
name = "charts"
version = "0.1.0"
description = ""
authors = ["Nathaniel Ledford <nate@nateledford.com>"]
readme = "README.md"
packages = [
    { include = "lastfm_stats", from = "src" }
]

[tool.poetry.dependencies]
python = "^3.12"
plotly = "^5.24.1"
requests = "^2.32.3"
pandas = "^2.2.3"
dash = "^2.18.2"
pydantic = "^2.10.3"
pylast = "^5.3.0"
python-dotenv = "^1.0.1"
aenum = "^3.1.15"
cuid2 = "^2.0.1"
cutlet = "^0.5.0"
unidic-lite = "^1.0.8"

[tool.poetry.group.test.dependencies]
pytest = "^8.3.4"

# Workaround to ensure numpy can be updated
[tool.poetry.dependencies.numpy]
git = "https://github.com/numpy/numpy"
rev = "7469245786b57405b7ae264b386400061b3b25d3"

[tool.poetry.scripts]
lastfm_stats = "lastfm_stats.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
include = ["src"]
exclude = [
    "**/node_modules",
    "**/__pycache__",
    "**/.idea",
    "**/.pytest_cache",
    "**/tests",
    "**/.git",
    "**/playground"
    #    "src/experimental",
    #    "src/typestubs"
]
#ignore = ["src/oldstuff"]
defineConstant = { DEBUG = true }
stubPath = "src/stubs"

reportMissingImports = "error"
reportMissingTypeStubs = false

pythonVersion = "3.13.1"
pythonPlatform = "Darwin"

#executionEnvironments = [
#    { root = "src/web", pythonVersion = "3.5", pythonPlatform = "Windows", extraPaths = [ "src/service_libs" ], reportMissingImports = "warning" },
#    { root = "src/sdk", pythonVersion = "3.0", extraPaths = [ "src/backend" ] },
#    { root = "src/tests", extraPaths = ["src/tests/e2e", "src/sdk" ]},
#    { root = "src" }
#]
