[tool.poetry]
name = "charts"
version = "0.1.0"
description = ""
authors = ["Nathaniel Ledford <nate@nateledford.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
plotly = "^5.24.1"
requests = "^2.32.3"
pandas = "^2.2.3"
dash = "^2.18.2"
pydantic = "^2.10.3"
pylast = "^5.3.0"
python-dotenv = "^1.0.1"
aenum = "^3.1.15"
pytest = "^8.3.4"
cuid2 = "^2.0.1"
cutlet = "^0.4.0"
unidic-lite = "^1.0.8"

# Workaround to ensure numpy can be updated
[tool.poetry.dependencies.numpy]
git = "https://github.com/numpy/numpy"
rev = "7469245786b57405b7ae264b386400061b3b25d3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
