[project]
name = "lastfm_stats"
version = "0.1.0"
description = ""
authors = [{ name = "Nathaniel Ledford", email = "<nate@nateledford.com>" }]
packages = [
    { include = "lastfm_stats", from = "src" }
]
requires-python = ">=3.13"
dependencies = [
    "requests (>=2.32.3,<3.0.0)",
    "aenum (>=3.1.15,<4.0.0)",
    "cuid2 (>=2.0.1,<3.0.0)",
    "cutlet (>=0.5.0,<0.6.0)",
    "dash (>=2.18.2,<3.0.0)",
    "numpy @ git+https://github.com/numpy/numpy@7469245786b57405b7ae264b386400061b3b25d3",
    "pandas (>=2.2.3,<3.0.0)",
    "plotly (>=5.24.1,<6.0.0)",
    "pydantic (>=2.10.5,<3.0.0)",
    "pylast (>=5.3.0,<6.0.0)",
    "pytest (>=8.3.4,<9.0.0)",
    "python-dotenv (>=1.0.1,<2.0.0)",
    "unidic-lite (>=1.0.8,<2.0.0)"
]

[tool.poetry]
packages = [{ include = "lastfm_stats", from = "src" }]

[project.scripts]
lastfm_stats = "lastfm_stats.main:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
include = ["src"]
exclude = [
    "**/node_modules",
    "**/__pycache__",
    "**/.idea",
    "**/.pytest_cache",
    "**/tests",
    "**/.git",
    "**/playground"
]
defineConstant = { DEBUG = true }
stubPath = "src/stubs"

reportMissingImports = "error"
reportMissingTypeStubs = false

pythonVersion = "3.13.1"
pythonPlatform = "Darwin"